// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDerivationBriefing(arg1) {
  return window['go']['wails']['DerivationBriefingsHandler']['GetDerivationBriefing'](arg1);
}

export function SendDerivationBriefMessage(arg1, arg2, arg3) {
  return window['go']['wails']['DerivationBriefingsHandler']['SendDerivationBriefMessage'](arg1, arg2, arg3);
}

export function StartDerivationBriefing(arg1, arg2) {
  return window['go']['wails']['DerivationBriefingsHandler']['StartDerivationBriefing'](arg1, arg2);
}
