// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wails} from '../models';

export function StartDerivationBriefing(arg1:string,arg2:string):Promise<wails.StartDerivationBriefingResponse>;
