// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wails} from '../models';

export function GetDerivationBriefing(arg1:string):Promise<wails.GetDerivationBriefingResponse>;

export function SendDerivationBriefMessage(arg1:string,arg2:string,arg3:string):Promise<wails.SendDerivationBriefMessageResponse>;

export function StartDerivationBriefing(arg1:string,arg2:string):Promise<wails.StartDerivationBriefingResponse>;
