// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function StartDerivationBriefing(arg1, arg2) {
  return window['go']['wails']['DerivationBriefingsHandler']['StartDerivationBriefing'](arg1, arg2);
}
