// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetEvaluationDetail(arg1) {
  return window['go']['wails']['ExperimentEvaluationDetailsHandler']['GetEvaluationDetail'](arg1);
}
