// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wails} from '../models';

export function FixExperimentConditions(arg1:wails.FixExperimentConditionsRequest):Promise<wails.FixExperimentConditionsResponse>;

export function GetExperimentPreparation(arg1:string):Promise<wails.GetExperimentPreparationResponse>;

export function SaveExperimentPreparationDraft(arg1:wails.SaveExperimentPreparationDraftRequest):Promise<wails.SaveExperimentPreparationDraftResponse>;
