// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function StartExperiment(arg1) {
  return window['go']['wails']['ExperimentRunsHandler']['StartExperiment'](arg1);
}
