// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function RetryEndedRun(arg1) {
  return window['go']['wails']['ExperimentRunRetriesHandler']['RetryEndedRun'](arg1);
}
