// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetExperimentBriefing(arg1) {
  return window['go']['wails']['ExperimentBriefingsHandler']['GetExperimentBriefing'](arg1);
}

export function SendExperimentBriefMessage(arg1, arg2, arg3) {
  return window['go']['wails']['ExperimentBriefingsHandler']['SendExperimentBriefMessage'](arg1, arg2, arg3);
}

export function StartExperimentBriefing(arg1) {
  return window['go']['wails']['ExperimentBriefingsHandler']['StartExperimentBriefing'](arg1);
}
