// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wails} from '../models';

export function RetryEndedRun(arg1:wails.RetryEndedRunRequest):Promise<wails.RetryEndedRunResponse>;
