// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wails} from '../models';

export function GetExperimentComparison(arg1:string):Promise<wails.GetExperimentComparisonResponse>;
