// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wails} from '../models';

export function GetExperimentBriefing(arg1:string):Promise<wails.GetExperimentBriefingResponse>;

export function StartExperimentBriefing(arg1:string):Promise<wails.StartExperimentBriefingResponse>;
