// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wails} from '../models';

export function CreateExperimentFromBrief(arg1:string,arg2:string,arg3:string):Promise<wails.CreateExperimentFromBriefResponse>;

export function GetExperimentBriefing(arg1:string):Promise<wails.GetExperimentBriefingResponse>;

export function SendExperimentBriefMessage(arg1:string,arg2:string,arg3:string):Promise<wails.SendExperimentBriefMessageResponse>;

export function StartExperimentBriefing(arg1:string):Promise<wails.StartExperimentBriefingResponse>;
