// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wails} from '../models';

export function CreateInsight(arg1:wails.CreateInsightRequest):Promise<wails.CreateInsightResponse>;

export function GetInsightWorkspace():Promise<wails.GetInsightWorkspaceResponse>;
