// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ListPreparations() {
  return window['go']['wails']['PreparationsHandler']['ListPreparations']();
}
