// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wails} from '../models';

export function GetPreparation(arg1:string):Promise<wails.GetPreparationResponse>;

export function ListPreparations():Promise<wails.ListPreparationsResponse>;

export function StartPreparation(arg1:string,arg2:string):Promise<wails.StartPreparationResponse>;
