// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AdoptCandidate(arg1, arg2, arg3) {
  return window['go']['wails']['PreparationsHandler']['AdoptCandidate'](arg1, arg2, arg3);
}

export function GetPreparation(arg1) {
  return window['go']['wails']['PreparationsHandler']['GetPreparation'](arg1);
}

export function ListPreparations() {
  return window['go']['wails']['PreparationsHandler']['ListPreparations']();
}

export function StartPreparation(arg1, arg2) {
  return window['go']['wails']['PreparationsHandler']['StartPreparation'](arg1, arg2);
}
